export const countries: Record<string, { name: string; flagIcon: string }> = {
    US: { name: 'United States', flagIcon: '🇺🇸' },
    CA: { name: 'Canada', flagIcon: '🇨🇦' },
    GB: { name: 'United Kingdom', flagIcon: '🇬🇧' },
    FR: { name: 'France', flagIcon: '🇫🇷' },
    DE: { name: 'Germany', flagIcon: '🇩🇪' },
    JP: { name: 'Japan', flagIcon: '🇯🇵' },
    IN: { name: 'India', flagIcon: '🇮🇳' },
    CN: { name: 'China', flagIcon: '🇨🇳' },
    BR: { name: 'Brazil', flagIcon: '🇧🇷' },
    AU: { name: 'Australia', flagIcon: '🇦🇺' },
    IT: { name: 'Italy', flagIcon: '🇮🇹' },
    RU: { name: 'Russia', flagIcon: '🇷🇺' },
    ZA: { name: 'South Africa', flagIcon: '🇿🇦' },
    MX: { name: 'Mexico', flagIcon: '🇲🇽' },
    KR: { name: 'South Korea', flagIcon: '🇰🇷' },
    NG: { name: 'Nigeria', flagIcon: '🇳🇬' },
    AR: { name: 'Argentina', flagIcon: '🇦🇷' },
    ES: { name: 'Spain', flagIcon: '🇪🇸' },
    NL: { name: 'Netherlands', flagIcon: '🇳🇱' },
    SE: { name: 'Sweden', flagIcon: '🇸🇪' },
    BE: { name: 'Belgium', flagIcon: '🇧🇪' },
    CH: { name: 'Switzerland', flagIcon: '🇨🇭' },
    AT: { name: 'Austria', flagIcon: '🇦🇹' },
    DK: { name: 'Denmark', flagIcon: '🇩🇰' },
    NO: { name: 'Norway', flagIcon: '🇳🇴' },
    FI: { name: 'Finland', flagIcon: '🇫🇮' },
    GR: { name: 'Greece', flagIcon: '🇬🇷' },
    PT: { name: 'Portugal', flagIcon: '🇵🇹' },
    IE: { name: 'Ireland', flagIcon: '🇮🇪' },
    PL: { name: 'Poland', flagIcon: '🇵🇱' },
    CZ: { name: 'Czech Republic', flagIcon: '🇨🇿' },
    HU: { name: 'Hungary', flagIcon: '🇭🇺' },
    RO: { name: 'Romania', flagIcon: '🇷🇴' },
    TR: { name: 'Turkey', flagIcon: '🇹🇷' },
    IL: { name: 'Israel', flagIcon: '🇮🇱' },
    SA: { name: 'Saudi Arabia', flagIcon: '🇸🇦' },
    EG: { name: 'Egypt', flagIcon: '🇪🇬' },
    KE: { name: 'Kenya', flagIcon: '🇰🇪' },
    GH: { name: 'Ghana', flagIcon: '🇬🇭' },
    TH: { name: 'Thailand', flagIcon: '🇹🇭' },
    MY: { name: 'Malaysia', flagIcon: '🇲🇾' },
    ID: { name: 'Indonesia', flagIcon: '🇮🇩' },
    VN: { name: 'Vietnam', flagIcon: '🇻🇳' },
    SG: { name: 'Singapore', flagIcon: '🇸🇬' },
    PH: { name: 'Philippines', flagIcon: '🇵🇭' },
    NZ: { name: 'New Zealand', flagIcon: '🇳🇿' },
    PK: { name: 'Pakistan', flagIcon: '🇵🇰' },
    BD: { name: 'Bangladesh', flagIcon: '🇧🇩' },
    CL: { name: 'Chile', flagIcon: '🇨🇱' },
    CO: { name: 'Colombia', flagIcon: '🇨🇴' },
    PE: { name: 'Peru', flagIcon: '🇵🇪' },
    VE: { name: 'Venezuela', flagIcon: '🇻🇪' },
    UA: { name: 'Ukraine', flagIcon: '🇺🇦' },
    KZ: { name: 'Kazakhstan', flagIcon: '🇰🇿' },
    AE: { name: 'United Arab Emirates', flagIcon: '🇦🇪' },
    QA: { name: 'Qatar', flagIcon: '🇶🇦' },
    KW: { name: 'Kuwait', flagIcon: '🇰🇼' },
    OM: { name: 'Oman', flagIcon: '🇴🇲' },
    BH: { name: 'Bahrain', flagIcon: '🇧🇭' },
    NG: { name: 'Nigeria', flagIcon: '🇳🇬' },
    TZ: { name: 'Tanzania', flagIcon: '🇹🇿' },
    UG: { name: 'Uganda', flagIcon: '🇺🇬' },
    ZM: { name: 'Zambia', flagIcon: '🇿🇲' },
    ZW: { name: 'Zimbabwe', flagIcon: '🇿🇼' },
    MZ: { name: 'Mozambique', flagIcon: '🇲🇿' },
    AO: { name: 'Angola', flagIcon: '🇦🇴' },
    CD: { name: 'Democratic Republic of the Congo', flagIcon: '🇨🇩' },
    MA: { name: 'Morocco', flagIcon: '🇲🇦' },
    DZ: { name: 'Algeria', flagIcon: '🇩🇿' },
    TN: { name: 'Tunisia', flagIcon: '🇹🇳' },
    LY: { name: 'Libya', flagIcon: '🇱🇾' },
    SD: { name: 'Sudan', flagIcon: '🇸🇩' },
    SN: { name: 'Senegal', flagIcon: '🇸🇳' },
    ET: { name: 'Ethiopia', flagIcon: '🇪🇹' },
    MG: { name: 'Madagascar', flagIcon: '🇲🇬' },
    MU: { name: 'Mauritius', flagIcon: '🇲🇺' },
    CY: { name: 'Cyprus', flagIcon: '🇨🇾' },
    MT: { name: 'Malta', flagIcon: '🇲🇹' },
    IS: { name: 'Iceland', flagIcon: '🇮🇸' },
    LU: { name: 'Luxembourg', flagIcon: '🇱🇺' },
    SI: { name: 'Slovenia', flagIcon: '🇸🇮' },
    SK: { name: 'Slovakia', flagIcon: '🇸🇰' },
    HR: { name: 'Croatia', flagIcon: '🇭🇷' },
    BG: { name: 'Bulgaria', flagIcon: '🇧🇬' },
    AL: { name: 'Albania', flagIcon: '🇦🇱' },
    RS: { name: 'Serbia', flagIcon: '🇷🇸' },
    MK: { name: 'North Macedonia', flagIcon: '🇲🇰' },
    LV: { name: 'Latvia', flagIcon: '🇱🇻' },
    LT: { name: 'Lithuania', flagIcon: '🇱🇹' },
    EE: { name: 'Estonia', flagIcon: '🇪🇪' },
    AM: { name: 'Armenia', flagIcon: '🇦🇲' },
    GE: { name: 'Georgia', flagIcon: '🇬🇪' },
    AZ: { name: 'Azerbaijan', flagIcon: '🇦🇿' },
    BY: { name: 'Belarus', flagIcon: '🇧🇾' },
    UZ: { name: 'Uzbekistan', flagIcon: '🇺🇿' },
    TM: { name: 'Turkmenistan', flagIcon: '🇹🇲' },
    TJ: { name: 'Tajikistan', flagIcon: '🇹🇯' },
    KG: { name: 'Kyrgyzstan', flagIcon: '🇰🇬' },
    MN: { name: 'Mongolia', flagIcon: '🇲🇳' },
    AF: { name: 'Afghanistan', flagIcon: '🇦🇫' },
    IR: { name: 'Iran', flagIcon: '🇮🇷' },
    IQ: { name: 'Iraq', flagIcon: '🇮🇶' },
    SY: { name: 'Syria', flagIcon: '🇸🇾' },
    LB: { name: 'Lebanon', flagIcon: '🇱🇧' },
    JO: { name: 'Jordan', flagIcon: '🇯🇴' },
    YE: { name: 'Yemen', flagIcon: '🇾🇪' },
    OM: { name: 'Oman', flagIcon: '🇴🇲' },
    KW: { name: 'Kuwait', flagIcon: '🇰🇼' },
    QA: { name: 'Qatar', flagIcon: '🇶🇦' },
    BH: { name: 'Bahrain', flagIcon: '🇧🇭' },
    MV: { name: 'Maldives', flagIcon: '🇲🇻' },
    LK: { name: 'Sri Lanka', flagIcon: '🇱🇰' },
    MM: { name: 'Myanmar', flagIcon: '🇲🇲' },
    KH: { name: 'Cambodia', flagIcon: '🇰🇭' },
    LA: { name: 'Laos', flagIcon: '🇱🇦' },
    BN: { name: 'Brunei', flagIcon: '🇧🇳' },
    TL: { name: 'Timor-Leste', flagIcon: '🇹🇱' },
    PG: { name: 'Papua New Guinea', flagIcon: '🇵🇬' },
    FJ: { name: 'Fiji', flagIcon: '🇫🇯' },
    SB: { name: 'Solomon Islands', flagIcon: '🇸🇧' },
    VU: { name: 'Vanuatu', flagIcon: '🇻🇺' },
    NC: { name: 'New Caledonia', flagIcon: '🇳🇨' },
    PF: { name: 'French Polynesia', flagIcon: '🇵🇫' },
    WF: { name: 'Wallis and Futuna', flagIcon: '🇼🇫' },
    KI: { name: 'Kiribati', flagIcon: '🇰🇮' },
    TO: { name: 'Tonga', flagIcon: '🇹🇴' },
    TV: { name: 'Tuvalu', flagIcon: '🇹🇻' },
    WS: { name: 'Samoa', flagIcon: '🇼🇸' },
    FM: { name: 'Micronesia', flagIcon: '🇫🇲' },
    MH: { name: 'Marshall Islands', flagIcon: '🇲🇭' },
    PW: { name: 'Palau', flagIcon: '🇵🇼' },
    NR: { name: 'Nauru', flagIcon: '🇳🇷' },
    SH: { name: 'Saint Helena', flagIcon: '🇸🇭' },
    KN: { name: 'Saint Kitts and Nevis', flagIcon: '🇰🇳' },
    LC: { name: 'Saint Lucia', flagIcon: '🇱🇨' },
    VC: { name: 'Saint Vincent and the Grenadines', flagIcon: '🇻🇨' },
    GD: { name: 'Grenada', flagIcon: '🇬🇩' },
    BB: { name: 'Barbados', flagIcon: '🇧🇧' },
    AG: { name: 'Antigua and Barbuda', flagIcon: '🇦🇬' },
    DM: { name: 'Dominica', flagIcon: '🇩🇲' },
    BZ: { name: 'Belize', flagIcon: '🇧🇿' },
    HN: { name: 'Honduras', flagIcon: '🇭🇳' },
    NI: { name: 'Nicaragua', flagIcon: '🇳🇮' },
    SV: { name: 'El Salvador', flagIcon: '🇸🇻' },
    CR: { name: 'Costa Rica', flagIcon: '🇨🇷' },
    PA: { name: 'Panama', flagIcon: '🇵🇦' },
    CU: { name: 'Cuba', flagIcon: '🇨🇺' },
    HT: { name: 'Haiti', flagIcon: '🇭🇹' },
    DO: { name: 'Dominican Republic', flagIcon: '🇩🇴' },
    JM: { name: 'Jamaica', flagIcon: '🇯🇲' },
    TT: { name: 'Trinidad and Tobago', flagIcon: '🇹🇹' },
    BS: { name: 'Bahamas', flagIcon: '🇧🇸' },
    AI: { name: 'Anguilla', flagIcon: '🇦🇮' },
    BM: { name: 'Bermuda', flagIcon: '🇧🇲' },
    VG: { name: 'British Virgin Islands', flagIcon: '🇻🇬' },
    TC: { name: 'Turks and Caicos Islands', flagIcon: '🇹🇨' },
    KY: { name: 'Cayman Islands', flagIcon: '🇰🇾' },
    MS: { name: 'Montserrat', flagIcon: '🇲🇸' },
    MP: { name: 'Northern Mariana Islands', flagIcon: '🇲🇵' },
    GU: { name: 'Guam', flagIcon: '🇬🇺' },
    AS: { name: 'American Samoa', flagIcon: '🇦🇸' },
    PR: { name: 'Puerto Rico', flagIcon: '🇵🇷' },
    VI: { name: 'U.S. Virgin Islands', flagIcon: '🇻🇮' },
    GL: { name: 'Greenland', flagIcon: '🇬🇱' },
    FO: { name: 'Faroe Islands', flagIcon: '🇫🇴' },
    SJ: { name: 'Svalbard and Jan Mayen', flagIcon: '🇸🇯' },
    YT: { name: 'Mayotte', flagIcon: '🇾🇹' },
    RE: { name: 'Réunion', flagIcon: '🇷🇪' },
    TF: { name: 'French Southern Territories', flagIcon: '🇹🇫' },
    NC: { name: 'New Caledonia', flagIcon: '🇳🇨' },
    GP: { name: 'Guadeloupe', flagIcon: '🇬🇵' },
    MQ: { name: 'Martinique', flagIcon: '🇲🇶' },
    BL: { name: 'Saint Barthélemy', flagIcon: '🇧🇱' },
    MF: { name: 'Saint Martin', flagIcon: '🇲🇫' },
    PM: { name: 'Saint Pierre and Miquelon', flagIcon: '🇵🇲' },
    WF: { name: 'Wallis and Futuna', flagIcon: '🇼🇫' },
  };
  
  